#pragma once

#ifdef DISABLE_NESTED_SPECULATION
#define MAX_CHECKPOINTS 1
#else
#define MAX_CHECKPOINTS 6

#define SPECFUZZ_PRIORITIZED_SIMULATION
#define BRANCH_FULL_EXEC_COUNT 5
#endif

#define SILENCE_GADGET_AFTER_FIRST_DISCOVERY
